
apiVersion: apimanagement.gloo.solo.io/v2
kind: GraphQLResolverMap
metadata:
  name: blogs
  namespace: gloo-mesh
spec:
  types:
    Query:
      fields:
        getBlogs:
          resolvers:
          - restResolver:
              destinations:
              - port:
                  number: 80
                ref:
                  name: blogs
                  namespace: default
              request:
                headers:
                  :path:
                    jq: '"/blogs"'
    Blog:
      fields:
        comments:
          variables:
            parentVar:
              graphqlParent: {}
          resolvers:
          - restResolver:
              destinations:
              - port:
                  number: 80
                ref:
                  name: comments
                  namespace: default
              request:
                headers:
                  :path:
                    jq: '"/comments?blogid=" + (.parentVar.id | tostring)'
        wordCount:  # NEW wordCount resolver begins HERE
          variables:
            parentBlog:
              graphqlParent: {}
          resolvers:
            - mockResolver:  # mockResolvers can facilitate testing too
                syncResponse:
                  jq: '.parentBlog.content | split(" ") | length'