apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: users
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - image: docker.io/asayah/users
        imagePullPolicy: Always
        name: users
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: docker.io/asayah/users-gql
        imagePullPolicy: Always
        name: users-gql
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File        

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: users
  name: users
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4000
  selector:
    app: users
  sessionAffinity: None
  type: ClusterIP