apiVersion: security.policy.gloo.solo.io/v2
kind: GraphQLAllowedQueryPolicy
metadata:
  name: blogs-allowed-queries
  namespace: gloo-mesh
spec:
  applyToRoutes:
  - route:
      labels:
        secured: "true"
  config:
    allowedQueryHashes: 
      - 2161a4f37fec6763a417a1bbf46c9a9d23d7fbfe8c110595fcf0bc1d2bb18a2e