
apiVersion: apimanagement.gloo.solo.io/v2
kind: GraphQLResolverMap
metadata:
  name: blogs
  namespace: gloo-mesh
spec:
  types:
    Query:
      fields:
        getBlogs:
          resolvers:
          - restResolver:
              destinations:
              - port:
                  number: 80
                ref:
                  name: blogs
                  namespace: default
              request:
                headers:
                  :path:
                    jq: '"/blogs"'