apiVersion: apimanagement.gloo.solo.io/v2
kind: GraphQLSchema
metadata:
  name: blogs
  namespace: gloo-mesh
spec:
  resolved:
    options: 
      enableIntrospection: true
    resolverMapRefs:
    - name: blogs
      namespace: gloo-mesh
      clusterName: gloo-gateway
  schemaRef:
    name: blogs
    namespace: gloo-mesh
    clusterName: gloo-gateway
