apiVersion: security.policy.gloo.solo.io/v2
kind: DLPPolicy
metadata:
  annotations:
  name: dlp
  namespace: gloo-mesh
spec:
  applyToRoutes:
  - route:
      labels:
        dlp: "true"
  config:
    actions:
    - customAction:
        maskChar: "*"
        name: test # only used for logging
        percent: 60
        regexActions:
        - regex: '"username":[^"]*"([^"]*)"'
          subgroup: 1