apiVersion: admin.gloo.solo.io/v2
kind: RateLimitServerSettings
metadata:
  name: rate-limit-server-settings
  namespace: gloo-mesh
spec:
  destinationServer:
    port:
      name: grpc
    ref:
      cluster: gloo-gateway
      name: rate-limiter
      namespace: gloo-mesh